Update azure-functions-app-python.yml

diff --git a/.github/workflows/azure-functions-app-python.yml b/.github/workflows/azure-functions-app-python.yml
--- a/.github/workflows/azure-functions-app-python.yml
+++ b/.github/workflows/azure-functions-app-python.yml
@@ -30,12 +30,18 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-pip-
 
-
-
       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+         if [ ! -f "$GITHUB_WORKSPACE/fnappwebresume/requirements.txt"]; 
+         then 
+            echo "$GITHUB_WORKSPACE/fnappwebresume/requirements.txt not found"
+            exit 1
+          fi
+
+          echo "install AZF requirements"
+          FILE_PATH = "$GITHUB_WORKSPACE/fnappwebresume/requirements.txt)
+          pip install -r FILE_PATH
       
       - name: Archive files
         run: |
